# Generated by Django 5.2.3 on 2025-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_contact",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="company_policies",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="working_hours",
            field=models.CharField(blank=True, null=True),
        ),
    ]
