# Generated by Django 5.2.3 on 2025-09-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_company_company_contact_company_company_policies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_contact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_policies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="working_hours",
            field=models.TextField(blank=True, null=True),
        ),
    ]
