# Generated by Django 5.2.3 on 2025-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_company_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='common_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='common_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
