# Generated by Django 5.2.3 on 2025-10-05 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_jsonfaq_alter_message_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="jsonfaq",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="json_fq",
                to="core.company",
            ),
            preserve_default=False,
        ),
    ]
