# Generated by Django 5.2.3 on 2025-10-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_websiteconfig_premium_llm_model_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="websiteconfig",
            options={"verbose_name": "LLM Config", "verbose_name_plural": "LLM Config"},
        ),
        migrations.AddField(
            model_name="websiteconfig",
            name="hardness_score",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="websiteconfig",
            name="llm_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gemini-2.5-flash", "gemini-2.5-flash"),
                    ("gemini-2.5-pro", "gemini-2.5-pro"),
                    ("deepseek/deepseek-chat-v3.1:free", "deepseek"),
                    ("other", "other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="websiteconfig",
            name="premium_llm_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gemini-2.5-flash", "gemini-2.5-flash"),
                    ("gemini-2.5-pro", "gemini-2.5-pro"),
                    ("deepseek/deepseek-chat-v3.1:free", "deepseek"),
                    ("other", "other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
