# Generated by Django 5.2.3 on 2025-10-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_whatsappmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappmessage",
            name="message_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
