# Generated by Django 5.2.3 on 2025-10-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_whatsappmessage_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Duration"
            ),
        ),
    ]
