# Generated by Django 6.0.3 on 2026-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_service_duration_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websiteconfig",
            name="llm_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gemini-2.5-flash", "gemini-2.5-flash"),
                    ("gemini-2.5-pro", "gemini-2.5-pro"),
                    ("deepseek/deepseek-chat-v3.1:free", "deepseek"),
                    ("other", "other"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="websiteconfig",
            name="premium_llm_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gemini-2.5-flash", "gemini-2.5-flash"),
                    ("gemini-2.5-pro", "gemini-2.5-pro"),
                    ("deepseek/deepseek-chat-v3.1:free", "deepseek"),
                    ("other", "other"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
