# Generated by Django 6.0.3 on 2026-09-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_booking_date_typed"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorSyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("company_info", "company_info"),
                            ("json_faq", "json_faq"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "op",
                    models.CharField(
                        choices=[("upsert", "upsert"), ("delete", "delete")],
                        default="upsert",
                        max_length=8,
                    ),
                ),
                (
                    "ref_id",
                    models.BigIntegerField(
                        help_text="Company pk for company_info, JSONFAQ pk for json_faq."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("done", "done"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_jobs",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_vector_status_0e4206_idx",
                    )
                ],
            },
        ),
    ]
